### ISSUE TITLE
How to get Results Reports as a String?

### ISSUE THREAD

**Issue by MourishS** [OleksandrKucherenko/meter#3]
Is it possible to get reports of the meter benchmark. In Logcat i get following results  
[ **I/meter: final: 43.130 ms (-0.085 ms), steps: 7**]. But unable to get as a string, in future using this results i will do some kind of validation purpose. Thanks and looking forward your reply!

**Comment by OleksandrKucherenko** [comment]
Just create a new logger that store everything into StringBuilder, for example, and use it...

more details about custom loggers:
https://github.com/OleksandrKucherenko/meter/blob/master/_documentation/logs.md

**Comment by OleksandrKucherenko** [comment]
another approach: 
https://github.com/OleksandrKucherenko/meter/blob/master/_documentation/testing.md
